### ISSUE TITLE
Ships extremely slow

### ISSUE THREAD

**Issue by DemonExposer** [Minecraft-Ships/ShipsForCore#17]
Version: 1.16.2 (Spigot)

When clicking the move sign, it takes multiple seconds before a small vessel moves.
In Ships 5, this behavior does not show. However, in Ships 5, the vessel breaks after using the wheel.
Please port Ships 5 to 1.16 because Ships 6 not only has bugs, it's also too difficult with the mandatory wool.

P.S. to configure the amount of wool needed it doesn't work when a ship is already made, but that is either another bug or a bad feature.

**Comment by mosemister** [comment]
Hi. 

Ships 6 is configured by default to be ran on even the weakest of servers without a drop in TPS (something Ships 5 was notorious for). 

You can change this in the ships 6 config to make it run a lot faster (some say faster then Ships 5). However if you rather have the way it was in Ships 5 then you can. You will see in the Ships 6 config two keys of "default" with the values ending in "ships_six" or "ships_five". If you change both these to "ships_five" then it will use the code from Ships 5. 

One thing to note, even if your running in Ships 5, there is a new value which is probably what is causing the most amount of slowness which is the "entity tracker" most servers will have this value set to 75 or higher. If you want the ships 5 experience then change this to 9999. 

As for porting Ships 5 to 1.16. it was attempted to be ported to 1.13+ in the form of Ships 5.1 however due to its reliance on Minecraft sub data values (as bukkit provided no good alternative at the time), it became too unstable which prevoked the work of Ships 6. So sorry but no im not going through that again. 

As for running Ships 5 on 1.16 now and the wheel breaking. While the Spigot team have made some improvements to the legacy backwards compatibility (which has improved running Ships on 1.13+) it hasnt got the legacy BukkitAPi  perfect (nor will it - the difference between 1.12.2 and 1.13 was too large for a API with the priority being forward compatible to handle) 

If you want help speeding up ships then please ask

**Comment by DemonExposer** [comment]
Thank you very much for this answer. I will try this and see how it works out.
I still find configuration a bit unclear without any explanation, but I am very very grateful for your explanation in this answer.

**Comment by mosemister** [comment]
Here is a explanation of some of the values in the config. It needs updating so not all the values are there but it will give you the main ones. 

https://dev.bukkit.org/projects/ships/pages/ships-6-page/ships-6-configuration

**Comment by DemonExposer** [comment]
Yes I saw that but it just isn't quite extensive enough, as you said, it needs updating.
I wish you good luck with that!

**Comment by mosemister** [comment]
When you say not extensive enough, do you mean the missing values or that the level of detail it goes into the current values isnt enough?

**Comment by DemonExposer** [comment]
The level of detail might be a bit low but overall that's quite okay. What I really mean is the missing values.

**Comment by mosemister** [comment]
Ok. Ill update it soon

**Comment by DemonExposer** [comment]
> there is a new value which is probably what is causing the most amount of slowness which is the "entity tracker"
Where do I find this?

**Comment by mosemister** [comment]
Updated 

https://dev.bukkit.org/projects/ships/pages/ships-6-page/ships-6-configuration

**Comment by mosemister** [comment]
Closed due to inactivity
