### ISSUE TITLE
Your vessel is already moving. Please wait for it to finish

### ISSUE THREAD

**Issue by AnakinTrotter** [Minecraft-Ships/ShipsForCore#5]
Airships can't move even with proper signs + burner and fuel

**To Reproduce**
1. Minecraft version 1.15.2
2. Spigot 1.15.2
3. Ships version 6.0.0.0 beta 2
4. Create an airship with license sign:

 [Ships]
Airship
Test
Beakguy2

5. Place move sign: [Move]
6. Right click move sign to increase speed
7. Left click move sign
8. Your vessel is already moving. Please wait for it to finish
9. Wait forever
10. Vessel still has not moved

**Comment by mosemister** [comment]
Any messages on the console? Typically that message occurs when booting ships and it fails to load the ship. 

Due to the fact you are not booting, it will be attempting to gather the structure of your ship but either you ship is so large in block count that it is taking forever, or something went wrong when gathering the structure

**Comment by mosemister** [comment]
closed due to lack communication
